name: 部署 VuePress 到 GitHub Pages

on:
  push:
    branches: [ main ]  # 触发分支，根据你的实际分支修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 使用 Node.js 18

      - name: 安装依赖
        run: npm install --frozen-lockfile

      - name: 构建文档
        run: |
          npm run build
          # 确保 .site 目录存在必要的文件
          touch .site/.nojekyll  # 防止 GitHub Pages 忽略下划线开头的文件
          # echo 'yourdomain.com' > .site/CNAME  # 如果有自定义域名

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置 token
          publish_dir: .site  # 你的构建输出目录
          keep_files: false   # 清除目标分支的旧文件
          force_orphan: true  # 强制使用单次提交
